name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ DOCKER_USERNAME }}/backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ DOCKER_USERNAME }}/frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ EC2_HOST }}
          username: ${{ EC2_USER }}
          key: ${{ EC2_SSH_KEY }}
          script: |
            cd DD-Intership-Task
            docker compose pull
            docker compose up -d
